version: '2.3'
services:
  pytorch:
    build: .
    runtime: nvidia
    ports:
      - $HOST_PORT:8888
    volumes:
      - $HOST_DIRECTORY:$CONTAINER_DIRECTORY
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --notebook-dir=$CONTAINER_DIRECTORY
